# coding: utf-8

"""
    InsightVM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.root_api import RootApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRootApi(unittest.TestCase):
    """RootApi unit test stubs"""

    def setUp(self):
        self.api = RootApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_resources(self):
        """Test case for resources

        Resources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
