# coding: utf-8

"""
    InsightVM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.credential_api import CredentialApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCredentialApi(unittest.TestCase):
    """CredentialApi unit test stubs"""

    def setUp(self):
        self.api = CredentialApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_shared_credential(self):
        """Test case for create_shared_credential

        Shared Credentials  # noqa: E501
        """
        pass

    def test_delete_all_shared_credentials(self):
        """Test case for delete_all_shared_credentials

        Shared Credentials  # noqa: E501
        """
        pass

    def test_delete_shared_credential(self):
        """Test case for delete_shared_credential

        Shared Credential  # noqa: E501
        """
        pass

    def test_get_shared_credential(self):
        """Test case for get_shared_credential

        Shared Credential  # noqa: E501
        """
        pass

    def test_get_shared_credentials(self):
        """Test case for get_shared_credentials

        Shared Credentials  # noqa: E501
        """
        pass

    def test_update_shared_credential(self):
        """Test case for update_shared_credential

        Shared Credential  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
