# coding: utf-8

"""
    InsightVM API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    Contact: support@rapid7.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scan_template_api import ScanTemplateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScanTemplateApi(unittest.TestCase):
    """ScanTemplateApi unit test stubs"""

    def setUp(self):
        self.api = ScanTemplateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_scan_template(self):
        """Test case for create_scan_template

        Scan Templates  # noqa: E501
        """
        pass

    def test_delete_scan_template(self):
        """Test case for delete_scan_template

        Scan Template  # noqa: E501
        """
        pass

    def test_get_scan_template(self):
        """Test case for get_scan_template

        Scan Template  # noqa: E501
        """
        pass

    def test_get_scan_templates(self):
        """Test case for get_scan_templates

        Scan Templates  # noqa: E501
        """
        pass

    def test_update_scan_template(self):
        """Test case for update_scan_template

        Scan Template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
